"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MERCHANT_BALANCE_ADJUSTMENT_REASON_TYPES = exports.MERCHANT_BALANCE_ADJUSTMENT_DEDUCT_REASON_TYPES = exports.MERCHANT_BALANCE_ADJUSTMENT_ADD_REASON_TYPES = exports.MERCHANT_BALANCE_ADJUSTMENT_ACTIONS = exports.MERCHANT_USER_SEARCH_FIELDS = void 0;
exports.MERCHANT_USER_SEARCH_FIELDS = ['phone', 'name'];
exports.MERCHANT_BALANCE_ADJUSTMENT_ACTIONS = ['add', 'deduct'];
exports.MERCHANT_BALANCE_ADJUSTMENT_ADD_REASON_TYPES = [
    '充值',
    '线下收款',
    '赠送',
    '优惠券',
    '其他'
];
exports.MERCHANT_BALANCE_ADJUSTMENT_DEDUCT_REASON_TYPES = [
    '退款',
    '取消赠送',
    '其他'
];
exports.MERCHANT_BALANCE_ADJUSTMENT_REASON_TYPES = [
    ...exports.MERCHANT_BALANCE_ADJUSTMENT_ADD_REASON_TYPES,
    ...exports.MERCHANT_BALANCE_ADJUSTMENT_DEDUCT_REASON_TYPES
];
