import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const scriptsDir = path.dirname(__filename);
const cloudFunctionsDir = path.resolve(scriptsDir, '..');
const repoRoot = path.resolve(cloudFunctionsDir, '..', '..');
const manifestPath = path.join(cloudFunctionsDir, 'cloudfunctions.json');
const packagePath = path.join(cloudFunctionsDir, 'package.json');
const buildRoot = path.join(cloudFunctionsDir, '.build');
const distRoot = path.join(cloudFunctionsDir, 'dist');
const functionsRoot = path.join(distRoot, 'functions');

function run(command, args, cwd) {
  const result = spawnSync(command, args, {
    cwd,
    stdio: 'inherit',
    shell: process.platform === 'win32'
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function ensureDir(dir) {
  mkdirSync(dir, { recursive: true });
}

function writeJson(filePath, value) {
  writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function visitFiles(dir, visitor) {
  if (!existsSync(dir)) {
    return;
  }

  for (const entry of readdirSync(dir)) {
    const entryPath = path.join(dir, entry);
    const stats = statSync(entryPath);

    if (stats.isDirectory()) {
      visitFiles(entryPath, visitor);
      continue;
    }

    visitor(entryPath);
  }
}

function compileTypescript(projectPath, outDir) {
  run('pnpm', ['exec', 'tsc', '--project', projectPath, '--outDir', outDir, '--declaration', 'false'], repoRoot);
}

function rewriteSharedImports(compiledFunctionsDir) {
  const cloudSourceDir = path.join(compiledFunctionsDir, 'apps', 'cloud-functions', 'src');
  const sharedSourceDir = path.join(compiledFunctionsDir, 'packages', 'shared', 'src');

  visitFiles(cloudSourceDir, (filePath) => {
    if (!filePath.endsWith('.js')) {
      return;
    }

    const source = readFileSync(filePath, 'utf8');
    const rewritten = source.replace(/require\(["']@xiaipet\/shared(?<subpath>\/[^"']*)?["']\)/g, (...args) => {
      const groups = args.at(-1);
      const subpath = groups?.subpath || '/index';
      const targetPath = path.join(sharedSourceDir, `${subpath.slice(1)}.js`);
      let relativePath = path.relative(path.dirname(filePath), targetPath).replaceAll(path.sep, '/');

      if (!relativePath.startsWith('.')) {
        relativePath = `./${relativePath}`;
      }

      return `require('${relativePath}')`;
    });

    if (rewritten !== source) {
      writeFileSync(filePath, rewritten, 'utf8');
    }
  });
}

function buildFunctionPackage(definition, compiledFunctionsDir, cloudPackage) {
  const entryRequirePath = `./cloud/${path
    .join('apps', 'cloud-functions', definition.source, 'index.js')
    .replaceAll(path.sep, '/')}`;
  const functionDir = path.join(functionsRoot, definition.name);
  const wxServerSdkVersion = cloudPackage.dependencies?.['wx-server-sdk'] || '^3.0.4';

  ensureDir(functionDir);

  cpSync(compiledFunctionsDir, path.join(functionDir, 'cloud'), { recursive: true });

  writeFileSync(
    path.join(functionDir, 'index.js'),
    `'use strict';\nexports.main = require('${entryRequirePath}').main;\n`,
    'utf8'
  );

  writeJson(path.join(functionDir, 'package.json'), {
    name: `xiaipet-cloud-${definition.name}`,
    private: true,
    main: 'index.js',
    dependencies: {
      'wx-server-sdk': wxServerSdkVersion
    }
  });
}

rmSync(buildRoot, { recursive: true, force: true });
rmSync(distRoot, { recursive: true, force: true });

ensureDir(buildRoot);
ensureDir(functionsRoot);

writeJson(path.join(functionsRoot, 'package.json'), {
  name: 'xiaipet-cloud-functions-root',
  private: true
});

const compiledFunctionsDir = path.join(buildRoot, 'cloud');
const cloudPackage = JSON.parse(readFileSync(packagePath, 'utf8'));

compileTypescript(path.join(cloudFunctionsDir, 'tsconfig.json'), compiledFunctionsDir);
rewriteSharedImports(compiledFunctionsDir);

const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
for (const definition of manifest.functions) {
  buildFunctionPackage(definition, compiledFunctionsDir, cloudPackage);
}

writeFileSync(
  path.join(distRoot, 'README.txt'),
  [
    'This directory is generated by apps/cloud-functions/scripts/build.mjs.',
    'Use render-deploy-config.mjs to create dist/cloudbaserc.json before running tcb functions:deploy.'
  ].join('\n'),
  'utf8'
);

if (!existsSync(functionsRoot)) {
  throw new Error('Function build output was not created.');
}
